sudo: required

language: node_js
node_js:
  - '8.11.1'

git:
  depth: 1

services:
  - docker

install:

script:
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
  - 'export VERSION=$(./scripts/current-version.js)'
  - 'docker image build -f ./docker/prod.Dockerfile -t haydenbr/new-years-api:$VERSION .'
  - 'docker image push haydenbr/new-years-api:$VERSION'
