version: '3.6'
services:
  new-years-api:
    container_name: new-years-api
    image: haydenbr/new-years-api:0.0.0
    depends_on:
      - new-years-mongo
    volumes:
      - ../src:/opt/app/src
      - ../package.json:/opt/app/package.json
    networks:
      - new-years-api
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://new-years-mongo:27017/new-years-resolutions

  new-years-mongo:
    container_name: new-years-mongo
    image: haydenbr/new-years-mongo
    volumes:
    - type: volume
      source: new-years-mongo
      target: /data/db
    networks:
      - new-years-api
    ports:
      - 27017:27017

volumes:
  new-years-mongo:

networks:
  new-years-api:
